### ISSUE TITLE
Data Collection at NodeConf NG

### ISSUE THREAD

**Issue by OpesanyaAdebayo** [nodejsnigeria/ecosystem#1]
To kickstart our ecosystem building efforts, we need to collect as much data as possible from those who attend the NodeConf NG. The data we collect might help us determine the order in which we execute our planned initiatives.

Off the top of my head, I think we should collect:
- Name
- Email
- Phone
- Gender
- Stack (Frontend/Backend/Full stack)
- Location (which state they're traveling from)
- Proficiency (Beginner/Intermediate/Senior)
- Mentorship interest (Whether they are interested in being mentors/mentees, which areas they are interested in mentoring/being mentored in)
- Employment status (Employed/Unemployed/Student, Current role, Looking to change jobs or not, Satisfied with pay or not)
- Other skills (writing, public speaking, e.t.c)
- General feedback/suggestions

We might not collect all these at once. We can share links to different forms at different points during the conference.

**Comment by segunadeleye** [comment]
This makes sense. Are we going to use a google form for this?

**Comment by pmbanugo** [comment]
Yes make sense, Did the registration form get all these info? Or do we create a google form and ask them to fill at the beginning of the conference?

**Comment by OpesanyaAdebayo** [comment]
Sadly, we didn't do this at the conference. However, we can still get data as we announce our smaller community initiatives, so we just get information relevant to the purpose of the initiative.

**Comment by segunadeleye** [comment]
We have emails of people who came for the event. How about we send them the form?

**Comment by OpesanyaAdebayo** [comment]
Okay. That's fine. Please check out [this form](https://docs.google.com/forms/d/1iHDRSPbp-nVBVdKp8HU77IRIkjTcuSMgHzLWR9KpPyU/edit) for your perusal. I guess we can start with this.

**Comment by segunadeleye** [comment]
Twitter handle.
GItHub profile/link/username

**Comment by OpesanyaAdebayo** [comment]
Thanks @segunadeleye. I've made the adjustments. Do you think we should send today?

**Comment by segunadeleye** [comment]
Not yet. We need to add those who wrote their names is the registration book.

**Comment by OpesanyaAdebayo** [comment]
Alright. Once we have a compiled list, then we can send.

**Comment by OpesanyaAdebayo** [comment]
Where are we on this?

**Comment by segunadeleye** [comment]
My bad, I have not typed out the names. I will get that done before the end of tomorrow 12/10/2018

**Comment by PrinceDavis** [comment]
Bros them, I hail oo!

I have a few things I would like to share, I understand that we are prioritizing helping the community members shape up their skills. I would suggest that before we go ahead to launch an initiative that we find a way to rank our member by competence level, so we can have apple data that would help guild subsequent decisions we would make. 

If we can do this well then whether we proceed with training or mentoring we would have means to measure the impact of such initiative on the community. 

I think we can do the ranking either through a survey or quiz.

**Comment by segunadeleye** [comment]
Thanks @PrinceDavis. We already made plans to send out surveys so we would have some information about those who make up the ecosystem.

If you have any idea of what should be in the survey, please let us know. Your contributions are highly welcome.

**Comment by OpesanyaAdebayo** [comment]
Closing this, because we never got to do it. I'll propose that we give out surveys at upcoming meetups and grow our database from there.

Please feel free to reopen if there are other ideas.
