### ISSUE TITLE
Engaging more intermediate/advanced members of our ecosystem

### ISSUE THREAD

**Issue by OpesanyaAdebayo** [nodejsnigeria/ecosystem#11]
Currently, our only effort towards ecosystem building is Training (#4 ), and it's quite beginner focused. For those who are intermediate/advanced, what we can do is make the final day of the training about one intermediate/advanced concept that may not have been covered in the training.
We can discuss issues like:
- Security
- Writing and publishing modules on NPM
- Scaling
- Debugging memory leaks
- Proper error handling
e.t.c.

This can also be a good avenue for beginners to meet with mentors who can help them in their journey. Also, it creates an atmosphere for networking and growth.

**Comment by segunadeleye** [comment]
I think we can cater to the intermediate/advanced members through meetups, where we can talk about these advanced concepts.

One way to engage them for the training is to invite some of them at different points during the training to take some of the classes.

**Comment by OpesanyaAdebayo** [comment]
Thanks @segunadeleye. I think we are still on the same page. What I'm just saying is that instead of organizing another meetup for intermediate/advanced folks, we can just do it as the final day of the training we are already doing periodically.
What I'm really trying to do here is to reduce the overhead of running meetups and also reduce segmentation.
> One way to engage them for the training is to invite some of them at different points during the training to take some of the classes.

👍:100:

**Comment by OpesanyaAdebayo** [comment]
Closing this for now, since our approach towards events this year (#13 ) helps solve this problem. Please feel free to reopen if you have other ideas.
