### ISSUE TITLE
Events for 2019

### ISSUE THREAD

**Issue by OpesanyaAdebayo** [nodejsnigeria/ecosystem#13]
I'm planning to reach out to potential sponsors soon, so I think we need to decide on what events we are having next year. I think we can do:
- One training for newer devs #4 (Jan-Feb or Feb-Mar)
- Global Diversity CFP Day #10 (March)
- One meetup for intermediate concepts (June)
- Conference (October)

Do you think this is okay?

**Comment by pmbanugo** [comment]
I think that's ok. October or November for the conference

**Comment by whiki** [comment]
This looks great! When does the planning begin?

**Comment by OpesanyaAdebayo** [comment]
Hi @whiki We aren't certain when exactly conference planning starts, but it will be within the next 2-3 months. Please follow us on [Twitter](https://twitter.com/nodejsnigeria) and watch this repo to stay updated.

**Comment by OpesanyaAdebayo** [comment]
After some deliberation, I think our calendar for this year should look like:

- Global Diversity CFP Day #10 (March)
- State of Node meetups bi-monthly (starting in April)
- Conference (October/November)

### State of Node meetups
To help us build momentum, we can actually have meetups bi-monthly. The nature of the meetups can be such that we discuss current trends, tools, tips and tricks that affect the way developers write, manage, and deploy Node.js code.
We can collaborate with other communities for these meetups. For examples, if we have a _State of Node: Devops_ meetup for example, we can collaborate with a community like Devops Lagos.

These State of Node meetups also help us create an inclusive community across all proficiency levels. See #11 .

**Comment by OpesanyaAdebayo** [comment]
At the last meeting, we concluded that the schedule is fine.

I'll be closing this issue for now. Please feel free to re-open if necessary.
