### ISSUE TITLE
Getting the community involved in our planning process

### ISSUE THREAD

**Issue by OpesanyaAdebayo** [nodejsnigeria/ecosystem#3]
I think from time to time, we can share selected issues here on Twitter and Slack with the community so we can make it easier for people to contribute and stay engaged. The decision on which issues should be shared can be discussed when we have our meetings.

**Comment by segunadeleye** [comment]
I like this. I want this node.js thing to be largely community driven...like GDG.

**Comment by OpesanyaAdebayo** [comment]
Closing this for now. Feel free to reopen if necessary.
