### ISSUE TITLE
Training Plans

### ISSUE THREAD

**Issue by OpesanyaAdebayo** [nodejsnigeria/ecosystem#4]
I think we should discuss training-specific issues in this thread.

Picking up from #2, we need to decide on a curriculum for the trainings. Any thoughts?

Also, we need to reach a consensus on:

- 1-day training or a series?
- On-site training or remote?
- Free training or paid?

I think we should reach the consensus on the training structure and model first. This will affect the curriculum.

**Comment by pmbanugo** [comment]
We don't have to do it all ourselves. I see NodeSchool Lagos, what about using their syllabus? looks good to me. There're already Chapters in Lagos. What about we use them to drive training? We can train alongside the trainers they already have.

I prefer 1 day free workshop. Maybe 10 to 20 persons but we need a space. I could speak to my employer and see if we can use office space but might take just 10 people except if we're doing a hackathon and it takes more.

**Comment by OpesanyaAdebayo** [comment]
Thanks @pmbanugo .

If we agree that NodeSchool curriculum is okay, then we're good.

I checked out NodeSchool Lagos and it doesn't seem like it's operational. You can check their [GitHub](https://github.com/nodeschool/lagos) and [website](https://nodeschool.io/lagos/).

I think someone tried to start it but it never took off.

If something can work out with your employer, that would be fantastic. We can use that to kick off an Abuja chapter. 👍🕺

**Comment by OpesanyaAdebayo** [comment]
If we want to run a 4-week training and we want the Global CFP Day workshop (#10) to be the week immediately after, then the training has to start January 19th, 2019. It means we have to double up on the planning for the training so we can make announcements early enough.

N.B: The presidential election is 16th February, so I already took this into account when making the calculation, considering the fact that we shouldn't have training that day.

**Comment by OpesanyaAdebayo** [comment]
I suggest we give free courses to a certain number of people at every meetup. That way, people learn on their own but we create an atmosphere that is beginner-friendly.

**Comment by OpesanyaAdebayo** [comment]
From our discussion at the last meeting, it's okay to give free courses to a certain number of people at every meetup to encourage beginners.

I'll be closing this issue for now. Feel free to re-open if necessary.
