### ISSUE TITLE
Website Redesign

### ISSUE THREAD

**Issue by OpesanyaAdebayo** [nodejsnigeria/ecosystem#6]
Our [current website](https://nigeria.nodejs.africa) contains only NodeConf NG content. I think we should take that off and upload a "coming soon" website while we build a new one that reflects who we are, what we are about and how people can join. We can have a separate website for future editions of NodeConf NG

**Comment by segunadeleye** [comment]
This makes sense.

Are we building a new one from scratch or modifying the one we used for the conference?

**Comment by OpesanyaAdebayo** [comment]
Please see [this issue](https://github.com/nodejsnigeria/nodejsnigeria-website/issues/2). I modified the one we used for conference, but it doesn't currently have conference information.

**Comment by OpesanyaAdebayo** [comment]
Closing this in favour of [this](https://github.com/nodejsnigeria/nodejsnigeria-website/issues/2)
